---
#The instances property of each host variable will be non-empty only when a fresh instance is created
#while the tagged_instances property will always be non-empty i.e.
#instances = tagged_instances; on a fresh instance
#instances = []; otherwise

- name: Ensure dynamic IP file is absent
  file: path="{{ansible_env.HOME}}/dynamic_ips_dev" state=absent

- name: Create file dynamic_ips
  file: path="{{ansible_env.HOME}}/dynamic_ips_dev" state=touch

- name: Launch Demo Server Instance
  ec2:
    exact_count: "{{demo.count}}"
    count_tag: "{{demo.node_tags}}"
    image: "{{demo.image}}"
    instance_tags: "{{demo.node_tags}}"
    instance_type: "{{demo.instance_type}}"
    region: "{{aws_region}}"
    wait: yes
    zone: "{{aws_zone}}"
  register: demo_server

- name: Create EBS Volume
  ec2_vol:
    instance: "{{ item.id }}"
    volume_size: "{{demo.ebs.volume_size}}"
    name: "{{demo.ebs.name}}"
    region: "{{aws_region}}"
  with_items: "{{ demo_server.instances }}"
  register: demo_ebs_vol

    
- name: Refresh EC2 cache
  command: "{{playbook_dir}}/ec2.py --refresh-cache"
  delegate_to: 127.0.0.1

- name: Refresh in-memory EC2 Cache
  meta: refresh_inventory


- name: Save satoshi server private IP to vars file
  lineinfile: line="satoshi_private_ip{{':'}} {{ item.private_ip }}"
              dest="{{ansible_env.HOME}}/dynamic_ips_dev"
  with_items: "{{demo_server.tagged_instances}}"